version: '3.9'

services:
  meal-service:
    build:
      context: ./meal-service
    container_name: meal-service
    depends_on:
      - mealdb
    networks:
      - surplusnet
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: 'postgresql://meal-service:password@mealdb:5432/mealdb'
  
  mealdb:
    image: postgres:15
    container_name: mealdb
    environment:
      POSTGRES_USER: meal-service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mealdb
    networks:
      - surplusnet
    volumes:
      - ./mealdb/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  surplusnet:
    driver: bridge

  
    